name: Check Community Approval

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

permissions:
  contents: read

jobs:
  check_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check for community approval
        run: |
          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'community-approved') }}" == "true" ]]; then
            echo "This PR has met the requirements for community approval."
          else
            echo "::error::This PR has not met the requirements for community approval."
            exit 1
          fi
